{% set name = "globus-nexus-client" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fabe10bfb0b5154e973436cc0e4473108b32835999512c5f20306635a8d87c19

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - globus-sdk >=1.0.0
    - six >=1.10.0

test:
  imports:
    - globus_nexus_client
  commands:
    - pip check

about:
  home: https://github.com/sirosen/globus-nexus-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: NexusClient object similar to Globus SDK objects

  description: |
    This is a personal project for talking to the Globus Nexus API with 
    all of the benefits of the Globus SDK. It is not a Globus maintained 
    product.
  doc_url: https://github.com/sirosen/globus-nexus-client
  dev_url: https://github.com/sirosen/globus-nexus-client

extra:
  recipe-maintainers:
    - jan-janssen
